# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# ## Site settings
# 
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be 
# accessible in the templates via {{ site.myvariable }}.
title: Stellar Firma Transcript Archive (Extremely Unofficial)
email: snarp@snarp.work
author: snarp
language: en-us
description: Transcripts of Stellar Firma podcast episodes.

# # If you're hosting your site at a Project repository on GitHub pages
# # (http://yourusername.github.io/repository-name)
# # and NOT your User repository (http://yourusername.github.io)
# # then add in the baseurl here, like this: "/repository-name"
# baseurl: "/repository-name"

permalink: /:categories/:title:output_ext

collections:
  news: 
    output: true

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false